name: Node.js CI CD
on:
  # trigger
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  # CD develop
  deploy:
    name: Deploy
    runs-on: ubuntu-lastest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CAPSTONE_HOST }}
          username: ${{ secrets.PRIVATE_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: | # run multiple script 
            cd /app/${GITHUB_REPOSITORY#*/}
            git checkout develop
            git pull origin develop
            git submodule update --init --recursive && \
            git submodule foreach git checkout develop && \
            git submodule foreach git pull origin develop
            npx ts-node index.ts
